python/django/odclinic/pacient/urls.py
from django.conf.urls.defaults import *
from odclinic.pacient.models import Pacient

dict_list_pacients = {'queryset': Pacient.objects.all(), 'template_object_name': 'pacient'}

urlpatterns = patterns('django.views.generic.list_detail',
    url(r'^$', 'object_list', dict_list_pacients, name="pacient-list"),
    url(r'^details/(?P<object_id>[\d]+)/$', 'object_detail', dict_list_pacients, name="pacient-detail"),    
)

urlpatterns += patterns('odclinic.pacient.views',
    url(r'^search/$', 'search', name='pacient-search'),
)

python/django/odclinic/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^odclinic/', include('odclinic.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    url(r'^pacient/', include('odclinic.pacient.urls')),
)

python/django/odclinic/pacient/models.py
from django.db import models
from django.contrib import admin

class Pacient(models.Model):
    GENDER_CHOICES = (
        (1, 'Male'),
        (2, 'Female'),
    )
    
    CIVIL_STATE_CHOICES = (
        (1, 'Single'),
        (2, 'Married'),
        (3, 'Divorced'),
        (4, 'Widower'),
    )
    
    STATUS_CHOICES = (
        (1, 'Active'),
        (2, 'Inactive'),
        (3, 'Return'),
        (4, 'Indebted'),
        (5, 'Defunct'),
    )
    
    name = models.CharField(max_length=128)
    cpf = models.CharField(max_length=12)
    rg = models.CharField(max_length=12) 
    gender = models.IntegerField(max_length=1, choices=GENDER_CHOICES)
    civil_state = models.IntegerField(max_length=1, choices=CIVIL_STATE_CHOICES)
    birth_date = models.DateField(null=True, blank=True)
    profession = models.CharField(max_length=128, null=True, blank=True)
    res_address = models.CharField(max_length=256)
    res_address_number = models.IntegerField()
    res_address_complement = models.CharField(max_length=5, null=True, blank=True)
    res_address_neighborhood = models.CharField(max_length=64, null=True, blank=True)
    res_address_zipcode = models.CharField(max_length=10, null=True, blank=True)
    res_phone = models.CharField(max_length=16, null=True, blank=True)
    com_address = models.CharField(max_length=256, null=True, blank=True)
    com_address_number = models.IntegerField(null=True, blank=True)
    com_address_complement = models.CharField(max_length=5, null=True, blank=True)
    com_address_neighborhood = models.CharField(max_length=64, null=True, blank=True)
    com_address_zipcode = models.CharField(max_length=10, null=True, blank=True)
    com_phone = models.CharField(max_length=16, null=True, blank=True)
    mobile = models.CharField(max_length=16, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)    
    indicated_by = models.ForeignKey('self', null=True, blank=True) 
    father_name = models.CharField(max_length=128, null=True, blank=True)
    mother_name = models.CharField(max_length=128, null=True, blank=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)     
    status = models.IntegerField(max_length=1, choices=STATUS_CHOICES, default=1)
    
    def get_formatted_res_address(self):
        parts = ''
        
        if self.res_address:
            parts = self.res_address
            
            if self.res_address_number:
                parts += ', ' + unicode(self.res_address_number)                
            if self.res_address_complement:
                parts += ', ' + unicode(self.res_address_complement)                
            parts += '. '
            
            if self.res_address_neighborhood:
                parts += self.res_address_neighborhood + '. '
            
            if self.res_address_zipcode:
                parts += unicode(self.res_address_zipcode) + '.'
                
        return parts.strip()
    
    def get_formatted_com_address(self):
        parts = ''
        
        if self.com_address:
            parts = self.com_address

            if self.com_address_number:
                parts += ', ' + unicode(self.com_address_number)                
            if self.com_address_complement:
                parts += ', ' + unicode(self.com_address_complement)                
            parts += '. '

            if self.com_address_neighborhood:
                parts += self.com_address_neighborhood + '. '

            if self.com_address_zipcode:
                parts += unicode(self.com_address_zipcode) + '.'

        return parts.strip()
    
    class Meta:
        ordering = ('name',)
        
    def __unicode__(self):        
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('pacient-detail', [str(self.id)])
        
class PacientAdmin(admin.ModelAdmin):
    list_display = ('name', 'mobile', 'res_phone', 'status',)
    search_fields = ('name', 'cpf', 'rg', 'indicated_by',)
    list_filter = ('name', 'status',)
    
class OfficeRoom(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField()
    is_active = models.BooleanField()
    
    def __unicode__(self):
        return self.name
    
class OfficeRoomAdmin(admin.ModelAdmin):
    list_display = ('name', 'description', 'is_active',)

class Schedule(models.Model):    
    pacient = models.ForeignKey(Pacient)
    office = models.ForeignKey(OfficeRoom)
    proceeding = models.ManyToManyField('Proceeding')
    detail = models.TextField()
    start = models.DateTimeField()
    end = models.DateTimeField()
    
class ScheduleAdmin(admin.ModelAdmin):
    list_display = ('pacient', 'office', 'start', 'end',)
    
class Proceeding(models.Model):
    name = models.CharField(max_length=128)
    detail = models.TextField()
    is_active = models.BooleanField()
    
    def __unicode__(self):
        return self.name

class ProceedingAdmin(admin.ModelAdmin):
    list_display = ('name', 'detail', 'is_active')

python/django/odclinic/pacient/views.py
from django.shortcuts import render_to_response, redirect
from odclinic.pacient.models import Pacient

def search(request):    
    '''
    Return a list of Pacient objects that match the provided
    search term in name.
    '''
    if 'q' in request.GET:
        pacient_list = Pacient.objects.filter(name__contains = request.GET['q'])
        
    return render_to_response('pacient/pacient_list.html', locals())
    

python/django/odclinic/pacient/templates/pacient/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>Clinica Odontológica Dr. Hamilton Renato :: {% block title %}{% endblock %}</title>
        <style type="text/css" media="screen">
          body {
            margin: 0;
            padding: 0;
            font-family: "Lucida Grande","Lucida Sans Unicode",Arial,Verdana,sans-serif;
            font-size: 14px;
          }
          #container {
            position: static;
            top: 0;
            left: 0;
          }
          #top {
            position: relative;
            background-color: #FFF;
            margin: 0;
            padding: 0 10px;
            border-bottom-style: dotted;
            height: 100px;
          }
          #banner {
            position: relative;
            top: 0;
            left: 0;
          }
          #topright {
            position: absolute;
            top: 0;
            right: 0;
            float: right;
          }
          #menu {
            position: absolute;
            right: 160px;
            top: 70px;
          }
          #menu ul li {
            display: inline;
          }
          #breadcrumb {
            position: relative;
            height: 30px;
            background-color: #FFF;
            border: 0 0 25px 0;
            padding: 10px;
            border-bottom-style: dotted;
          }
          #middle {
            width: 70%;
            margin-right: 15%;
            margin-left: 15%;
          }
          #foot {
            height: 100px;
            background-color: #000;
            color: white;
            margin: 50px 0;
          }
        </style>               
    </head>
    <body>
        <div id="container">
            <div id="top">
              <div id="banner">
                <h1>Clinica Odontológica Dr. Hamilton Renato</h1>
              </div>
              <div id="topright">
                <form action="{% url pacient-search %}" method="get" accept-charset="utf-8">    
                  <p><input type="text" id="search_field" name="q"/></p>
                </form>
              </div>              
              <div id="menu">
                <ul>
                  <li><a href="{% url pacient-list %}">Pacients</a></li>
                  <li>Schedule</li>
                </ul>
              </div>
            </div>
            
            <div id="breadcrumb">
              
            </div>
            <div id="middle">                
                {% block content %}
                {% endblock %}  
            </div>
            <div id="foot">
              ODClinic v0.1 - gustavofons@gmail.com
            </div>
        </div>        
    </body>
</html>

python/django/odclinic/pacient/templates/pacient/pacient_detail.html
{% extends "pacient/base.html" %}

{% block title %}Detalhes de {{ pacient.name }}{% endblock %}

{% block content %}
<span class="vcard">
  <h2>Details of <span class="fn">{{ pacient.name }}</span></h2>
  <h4>Status {{ pacient.get_status_display }}</h4>
  * histórico
  <fieldset id="contact">
      <legend>Contact</legend>
      <strong>Mobile:</strong> {{ pacient.mobile }}<br/>
      <strong>Residence:</strong> {{ pacient.res_phone }}<br/>
      <strong>Work:</strong> {{ pacient.com_phone }}<br/>
      <strong>Res. Address:</strong> {{ pacient.get_formatted_res_address }}<br/>
      <strong>Work Address:</strong> {{ pacient.get_formatted_com_address }}<br/>
      <strong>Email:</strong> <a href="mailto:{{ pacient.email }}">{{ pacient.email }}</a><br/>
    
  </fieldset>
  <fieldset id="personal-info">
      <legend>Info</legend>
      <strong>CPF:</strong> {{ pacient.cpf }}<br/>
      <strong>RG:</strong> {{ pacient.rg }}<br/>
      <strong>Birth:</strong> {{ pacient.birth_date }}<br/>
      <strong>Civil State:</strong> {{ pacient.get_civil_state_display }}<br/>
      <strong>Gender:</strong> {{ pacient.get_gender_display }}<br/>
      <strong>Profession:</strong> {{ pacient.profession }}
  </fieldset>

  <p class="small">Created at {{ pacient.created_at }} | Modified at {{ pacient.updated_at }}.</p>

  <a href="{% url pacient-list %}">Back</a>
</span>
{% endblock %}

python/django/odclinic/pacient/templates/pacient/pacient_list.html
{% extends "pacient/base.html" %}

{% block title %}Listagem de Pacientes{% endblock %}

<style type="text/css" media="screen">
    span.name {
        color: red;
    }
</style>

{% block content %}
<ul>  
{% for pacient in pacient_list %}
    <li>
        <span class="name"><a href="{{ pacient.get_absolute_url }}">{{ pacient.name }}</a></span><br/>
        Mobile: {{ pacient.mobile }}<br/>
        Status: {{ pacient.get_status_display }}
    </li>
{% endfor %}
</ul>
{% endblock %}